from odoo import api, fields, models, _
from odoo.exceptions import UserError, ValidationError
from datetime import datetime, date, time
import logging

_logger = logging.getLogger(__name__)


class PosZReading(models.Model):
    """
    Z-Reading Report Model for BIR Compliance
    
    A Z-reading is a daily summary report that RESETS counters.
    - Can only be generated ONCE per calendar date
    - All POS sessions for that date MUST be closed
    - Required for BIR compliance and tax reporting
    """
    _name = 'pos.zreading'
    _description = 'POS Z-Reading Report'
    _order = 'reading_date desc, id desc'
    _rec_name = 'reading_number'

    # ========== Header Information ==========
    reading_number = fields.Char(
        string='Z-Reading Number',
        required=True,
        readonly=True,
        copy=False,
        index=True,
        default='New',
        help='Sequential Z-reading number (Z-counter)')
    
    reading_date = fields.Date(
        string='Reading Date',
        required=True,
        readonly=True,
        default=fields.Date.context_today,
        help='Business date for this Z-reading')
    
    reading_datetime = fields.Datetime(
        string='Reading Date & Time',
        readonly=True,
        default=fields.Datetime.now,
        help='Actual date and time when Z-reading was generated')
    
    company_id = fields.Many2one(
        'res.company',
        string='Company',
        required=True,
        readonly=True,
        default=lambda self: self.env.company)
    
    currency_id = fields.Many2one(
        'res.currency',
        string='Currency',
        related='company_id.currency_id',
        readonly=True)
    
    bir_config_id = fields.Many2one(
        'bir.config',
        string='BIR Configuration',
        readonly=True,
        help='BIR configuration at time of reading')
    
    user_id = fields.Many2one(
        'res.users',
        string='Generated By',
        required=True,
        readonly=True,
        default=lambda self: self.env.user,
        help='User who generated this Z-reading')
    
    # ========== Transaction Counts ==========
    transaction_count = fields.Integer(
        string='Total Transactions',
        readonly=True,
        help='Number of completed transactions')
    
    session_count = fields.Integer(
        string='Sessions',
        readonly=True,
        help='Number of POS sessions for this date')
    
    voided_transaction_count = fields.Integer(
        string='Voided Transactions',
        readonly=True,
        help='Number of voided transactions')
    
    # ========== Sales Amounts ==========
    gross_sales = fields.Monetary(
        string='Gross Sales',
        readonly=True,
        currency_field='currency_id',
        help='Total sales before discounts')
    
    total_discounts = fields.Monetary(
        string='Total Discounts',
        readonly=True,
        currency_field='currency_id',
        help='Total amount of all discounts')
    
    net_sales = fields.Monetary(
        string='Net Sales',
        readonly=True,
        currency_field='currency_id',
        help='Sales after discounts')
    
    # ========== VAT Breakdown ==========
    vatable_sales = fields.Monetary(
        string='VATable Sales',
        readonly=True,
        currency_field='currency_id',
        help='Sales subject to 12% VAT (net of VAT)')
    
    vat_amount = fields.Monetary(
        string='VAT Amount (12%)',
        readonly=True,
        currency_field='currency_id',
        help='12% VAT on VATable sales')
    
    vat_exempt_sales = fields.Monetary(
        string='VAT-Exempt Sales',
        readonly=True,
        currency_field='currency_id',
        help='Sales exempt from VAT (SC/PWD discounts)')
    
    zero_rated_sales = fields.Monetary(
        string='Zero-Rated Sales',
        readonly=True,
        currency_field='currency_id',
        help='Zero-rated sales')
    
    # ========== Voided Amounts ==========
    voided_amount = fields.Monetary(
        string='Voided Amount',
        readonly=True,
        currency_field='currency_id',
        help='Total amount of voided transactions')
    
    # ========== Refund Amounts ==========
    refund_count = fields.Integer(
        string='Refund Transactions',
        readonly=True,
        help='Number of refund transactions')
    
    refund_amount = fields.Monetary(
        string='Refund Amount',
        readonly=True,
        currency_field='currency_id',
        help='Total amount of refund transactions (shown as positive value)')
    
    # ========== Payment Breakdown ==========
    cash_payments = fields.Monetary(
        string='Cash Payments',
        readonly=True,
        currency_field='currency_id')
    
    card_payments = fields.Monetary(
        string='Card Payments',
        readonly=True,
        currency_field='currency_id')
    
    other_payments = fields.Monetary(
        string='Other Payments',
        readonly=True,
        currency_field='currency_id')
    
    # ========== Grand Totals ==========
    old_grand_total = fields.Monetary(
        string='Old Grand Total',
        readonly=True,
        currency_field='currency_id',
        help='Accumulated total before this Z-reading')
    
    new_grand_total = fields.Monetary(
        string='New Grand Total',
        readonly=True,
        currency_field='currency_id',
        help='Accumulated total after this Z-reading')
    
    # ========== Status ==========
    state = fields.Selection([
        ('draft', 'Draft'),
        ('confirmed', 'Confirmed'),
        ('printed', 'Printed'),
    ], string='Status', default='draft', readonly=True)
    
    # ========== Constraints ==========
    _sql_constraints = [
        ('unique_reading_date_company', 
         'UNIQUE(reading_date, company_id)', 
         'Only one Z-reading can be generated per date per company!')
    ]

    @api.model_create_multi
    def create(self, vals_list):
        """Generate sequential reading numbers"""
        for vals in vals_list:
            if vals.get('reading_number', 'New') == 'New':
                # Get BIR config for Z-counter
                company_id = vals.get('company_id', self.env.company.id)
                bir_config = self.env['bir.config'].search([
                    ('company_id', '=', company_id)
                ], limit=1)
                
                z_counter = bir_config.z_reading_counter + 1 if bir_config else 1
                vals['reading_number'] = f"Z-{z_counter:04d}"
        
        return super().create(vals_list)

    @api.model
    def generate_zreading(self, reading_date):
        """
        Generate Z-Reading for a specific date
        
        This method:
        1. Validates that no Z-reading exists for this date
        2. Validates that ALL sessions for this date are closed
        3. Validates that there are transactions for this date
        4. Calculates all totals
        5. Creates Z-reading record
        6. Increments Z-counter in BIR config
        7. Updates last Z-reading date in BIR config
        
        Args:
            reading_date: Date object or string in YYYY-MM-DD format
            
        Returns:
            Created Z-reading record
            
        Raises:
            UserError: If validation fails
        """
        # Convert string to date if needed
        if isinstance(reading_date, str):
            reading_date = fields.Date.from_string(reading_date)
        
        company = self.env.company
        
        _logger.info(f"Starting Z-reading generation for {reading_date}")
        
        # ========== VALIDATION 1: Check if Z-reading already exists ==========
        existing = self.search([
            ('reading_date', '=', reading_date),
            ('company_id', '=', company.id)
        ])
        if existing:
            raise UserError(
                f"Z-reading already exists for {reading_date}!\n\n"
                f"Z-Reading Number: {existing.reading_number}\n"
                f"Generated on: {existing.reading_datetime}\n"
                f"Generated by: {existing.user_id.name}\n\n"
                "Only ONE Z-reading per date is allowed."
            )
        
        # ========== VALIDATION 2: Check if all sessions are closed ==========
        date_start = datetime.combine(reading_date, time.min)
        date_end = datetime.combine(reading_date, time.max)
        
        all_sessions = self.env['pos.session'].search([
            ('start_at', '>=', date_start),
            ('start_at', '<=', date_end),
            ('company_id', '=', company.id)
        ])
        
        open_sessions = all_sessions.filtered(lambda s: s.state != 'closed')
        
        if open_sessions:
            session_list = '\n'.join([
                f"  • {s.name} - Started: {s.start_at.strftime('%I:%M %p')} - User: {s.user_id.name}"
                for s in open_sessions
            ])
            raise UserError(
                f"❌ Cannot generate Z-reading for {reading_date}\n\n"
                f"There are {len(open_sessions)} OPEN session(s) for this date:\n\n"
                f"{session_list}\n\n"
                "All sessions must be CLOSED before generating Z-reading.\n"
                "Please close all sessions first."
            )
        
        _logger.info(f"Validation passed: {len(all_sessions)} session(s) are all closed")
        
        # ========== VALIDATION 3: Check if there are transactions ==========
        orders = self.env['pos.order'].search([
            ('date_order', '>=', date_start),
            ('date_order', '<=', date_end),
            ('state', 'in', ['paid', 'done', 'invoiced']),
            ('is_voided', '=', False),
            ('company_id', '=', company.id)
        ])
        
        if not orders:
            raise UserError(
                f"No transactions found for {reading_date}.\n\n"
                "Cannot generate Z-reading for a date with no sales.\n"
                "If this date should have sales, please check:\n"
                "  • Order dates are correct\n"
                "  • Orders are in 'paid', 'done', or 'invoiced' state\n"
                "  • Orders are not voided"
            )
        
        _logger.info(f"Found {len(orders)} orders for Z-reading")
        
        # ========== Get voided orders ==========
        voided_orders = self.env['pos.order'].search([
            ('date_order', '>=', date_start),
            ('date_order', '<=', date_end),
            ('is_voided', '=', True),
            ('company_id', '=', company.id)
        ])
        
        # ========== Get refund orders ==========
        # Refund orders have negative amount_total (items returned)
        refund_orders = self.env['pos.order'].search([
            ('date_order', '>=', date_start),
            ('date_order', '<=', date_end),
            ('state', 'in', ['paid', 'done', 'invoiced']),
            ('is_voided', '=', False),
            ('amount_total', '<', 0),
            ('company_id', '=', company.id)
        ])
        
        _logger.info(f"Found {len(refund_orders)} refund orders for Z-reading")
        
        # ========== Calculate totals ==========
        totals = self._calculate_totals(orders, voided_orders, refund_orders)
        
        # ========== Get BIR config ==========
        bir_config = self.env['bir.config'].search([
            ('company_id', '=', company.id)
        ], limit=1)
        
        # Calculate old grand total (from last Z-reading)
        last_zreading = self.search([
            ('reading_date', '<', reading_date),
            ('company_id', '=', company.id)
        ], order='reading_date desc', limit=1)
        
        old_grand_total = last_zreading.new_grand_total if last_zreading else 0.0
        new_grand_total = old_grand_total + totals['net_sales']
        
        # ========== Create Z-reading record ==========
        zreading_vals = {
            'reading_date': reading_date,
            'reading_datetime': fields.Datetime.now(),
            'bir_config_id': bir_config.id if bir_config else False,
            'company_id': company.id,
            
            # Transaction counts
            'transaction_count': len(orders),
            'session_count': len(all_sessions),
            'voided_transaction_count': len(voided_orders),
            
            # Sales amounts
            'gross_sales': totals['gross_sales'],
            'total_discounts': totals['total_discounts'],
            'net_sales': totals['net_sales'],
            
            # VAT breakdown
            'vatable_sales': totals['vatable_sales'],
            'vat_amount': totals['vat_amount'],
            'vat_exempt_sales': totals['vat_exempt_sales'],
            'zero_rated_sales': totals['zero_rated_sales'],
            
            # Voided
            'voided_amount': totals['voided_amount'],
            
            # Refunds
            'refund_count': totals['refund_count'],
            'refund_amount': totals['refund_amount'],
            
            # Payments
            'cash_payments': totals['cash_payments'],
            'card_payments': totals['card_payments'],
            'other_payments': totals['other_payments'],
            
            # Grand totals
            'old_grand_total': old_grand_total,
            'new_grand_total': new_grand_total,
            
            'state': 'confirmed',  # Z-reading is immediately confirmed
        }
        
        zreading = self.create(zreading_vals)
        _logger.info(f"Z-reading {zreading.reading_number} created successfully")
        
        # ========== Update BIR config ==========
        if bir_config:
            bir_config.increment_z_reading()
            _logger.info(f"Z-counter incremented to {bir_config.z_reading_counter}")
        
        return zreading

    def _calculate_totals(self, orders, voided_orders, refund_orders=None):
        """Calculate all financial totals for Z-reading
        
        BIR Calculation Rules (per order line):
        - For VAT-exempt discountable items (SC/PWD): 
          - Gross = original VAT-inclusive price (what customer would pay without discount)
          - VAT-exempt base = Gross / 1.12 (VAT removed)
          - Discount = VAT-exempt base * discount_percent (SC/PWD discount on VAT-exempt amount)
          - Total Discounts = Discount only (not including VAT removed - that's a VAT exemption, not a discount)
          - Final = VAT-exempt base * (1 - discount_percent)
        - For non-discountable items in VAT-exempt orders:
          - Treated as regular VATable sales
        - For regular VATable orders: gross = amount_total, VAT = amount_tax
        - For zero-rated orders: gross = amount_total, no VAT
        - Refund orders (negative amount_total) are tracked separately
        """
        if refund_orders is None:
            refund_orders = self.env['pos.order']
        
        totals = {
            'gross_sales': 0.0,
            'total_discounts': 0.0,
            'net_sales': 0.0,
            'vatable_sales': 0.0,
            'vat_amount': 0.0,
            'vat_exempt_sales': 0.0,
            'zero_rated_sales': 0.0,
            'voided_amount': 0.0,
            'refund_count': 0,
            'refund_amount': 0.0,
            'cash_payments': 0.0,
            'card_payments': 0.0,
            'other_payments': 0.0,
        }
        
        for order in orders:
            # Check if this is a VAT-exempt order (SC/PWD)
            # SC and PWD are ALWAYS VAT-exempt by BIR rules, regardless of is_vat_exempt flag
            is_vat_exempt_order = False
            if order.bir_discount_type_id:
                discount_type = order.bir_discount_type_id
                discount_type_code = discount_type.discount_type  # Selection: 'sc', 'pwd', etc.
                discount_code = (discount_type.code or '').upper().strip()  # Free text code
                
                # Check both discount_type selection AND code field (case-insensitive)
                # This handles cases where user set code="SC" but left discount_type as default
                is_sc_or_pwd = (
                    discount_type_code in ('sc', 'pwd') or
                    discount_code in ('SC', 'SENIOR', 'SENIOR CITIZEN', 'PWD', 'DISABLED')
                )
                is_vat_exempt_order = discount_type.is_vat_exempt or is_sc_or_pwd
            
            if is_vat_exempt_order:
                discount_percent = order.bir_discount_type_id.discount_percent / 100.0
                
                # Process each order line separately
                for line in order.lines:
                    line_total = line.price_subtotal_incl  # Final price paid for this line
                    original_price = line.price_unit * line.qty  # Original price before any discount
                    
                    # Check if this product is discountable
                    is_discountable = getattr(line.product_id, 'is_bir_discountable', True)
                    if is_discountable is None:
                        is_discountable = True  # Default to True if field doesn't exist
                    
                    if is_discountable and discount_percent > 0:
                        # For discountable items with VAT-exempt discount:
                        # BIR Formula: Remove VAT first (÷1.12), then apply discount
                        # 
                        # Example: 140 item with 20% SC discount:
                        # - VAT-exempt base = 140 / 1.12 = 125
                        # - SC Discount = 125 * 20% = 25 (this is the ONLY discount shown)
                        # - Final = 125 - 25 = 100
                        #
                        # Gross Sales should be the VAT-exempt base (125), NOT original price (140)
                        # because the VAT was never collected (it's exempt, not discounted)
                        
                        vat_exempt_base = original_price / 1.12
                        # The discount is applied on the VAT-exempt amount
                        discount_amount = vat_exempt_base * discount_percent
                        
                        # Gross = VAT-exempt base (this is the taxable gross before discount)
                        totals['gross_sales'] += vat_exempt_base
                        # Discount = only the SC/PWD discount (not VAT removed)
                        totals['total_discounts'] += discount_amount
                        # VAT-exempt sales = final amount after discount
                        totals['vat_exempt_sales'] += line_total
                    else:
                        # For non-discountable items: treat as regular VATable
                        # Even in a VAT-exempt order, non-discountable items remain VATable
                        totals['gross_sales'] += original_price
                        
                        # Calculate VAT (assuming 12% VAT inclusive price)
                        vat_amount = original_price - (original_price / 1.12)
                        vatable_base = original_price - vat_amount
                        
                        totals['vatable_sales'] += vatable_base
                        totals['vat_amount'] += vat_amount
            else:
                # For regular orders (non VAT-exempt)
                # Use bir_discount_amount ONLY if there's no VAT-exempt discount
                # For non-VAT-exempt discounts, bir_discount_amount stores the actual discount
                if order.bir_discount_amount and order.bir_discount_amount > 0:
                    # bir_discount_amount should be just the discount portion, not including VAT
                    gross = order.amount_total + order.bir_discount_amount
                    totals['total_discounts'] += order.bir_discount_amount
                else:
                    gross = order.amount_total
                
                totals['gross_sales'] += gross
                
                # VAT breakdown: use actual order.amount_tax to determine VATable vs zero-rated
                if order.amount_tax and order.amount_tax > 0:
                    # VATable order
                    totals['vatable_sales'] += order.amount_total - order.amount_tax
                    totals['vat_amount'] += order.amount_tax
                else:
                    # Zero-rated sales
                    totals['zero_rated_sales'] += order.amount_total
            
            # Net sales (always the final amount paid)
            totals['net_sales'] += order.amount_total
            
            # Payment breakdown
            for payment in order.payment_ids:
                if payment.payment_method_id.is_cash_count:
                    totals['cash_payments'] += payment.amount
                elif 'card' in payment.payment_method_id.name.lower():
                    totals['card_payments'] += payment.amount
                else:
                    totals['other_payments'] += payment.amount
        
        # Voided amounts
        for voided in voided_orders:
            totals['voided_amount'] += voided.amount_total
        
        # Refund amounts (negative orders are refunds)
        # Store as positive value for display
        totals['refund_count'] = len(refund_orders)
        for refund in refund_orders:
            # amount_total is negative for refunds, so we use abs()
            totals['refund_amount'] += abs(refund.amount_total)
        
        return totals

    def action_print_zreading(self):
        """Print Z-reading report - Direct PDF download"""
        self.ensure_one()
        self.write({'state': 'printed'})
        
        # Get the report and generate PDF directly
        report = self.env.ref('cai_pos.action_report_pos_zreading')
        
        # Return action to open PDF in new window
        return {
            'type': 'ir.actions.act_url',
            'url': f'/report/pdf/cai_pos.report_pos_zreading_document/{self.id}',
            'target': 'new',
        }

