from odoo import api, fields, models, _
from odoo.exceptions import UserError, ValidationError
from datetime import datetime, date, time
import csv
import io
import base64
import logging
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill
from openpyxl.utils import get_column_letter

_logger = logging.getLogger(__name__)


class PosEsalesReport(models.Model):
    """
    BIR eSales Monthly Report Model
    
    Generates CSV files for BIR monthly submission as per requirements:
    - Filename format: POS SALES [TIN][BranchCode] MMYYYY F[Series].CSV
    - Max 999 data rows per file (split into multiple files if needed)
    - Includes daily sales summary with all required columns
    """
    _name = 'pos.esales.report'
    _description = 'BIR eSales Monthly Report'
    _order = 'report_month desc'
    
    name = fields.Char(
        string='Report Name',
        compute='_compute_name',
        store=True)
    
    report_month = fields.Date(
        string='Report Month',
        required=True,
        help='Month for which eSales report is generated (first day of month)')
    
    company_id = fields.Many2one(
        'res.company',
        string='Company',
        required=True,
        readonly=True,
        default=lambda self: self.env.company)
    
    bir_config_id = fields.Many2one(
        'bir.config',
        string='BIR Configuration',
        required=True,
        readonly=True,
        help='BIR configuration used for this report')
    
    currency_id = fields.Many2one(
        'res.currency',
        string='Currency',
        related='company_id.currency_id',
        readonly=True)
    
    # File details
    filename = fields.Char(
        string='Filename',
        compute='_compute_filename',
        store=True,
        help='Generated filename as per BIR format')
    
    csv_file = fields.Binary(
        string='CSV File',
        readonly=True,
        help='Generated CSV file')
    
    csv_filename = fields.Char(
        string='CSV Filename',
        readonly=True)
    
    excel_file = fields.Binary(
        string='Excel File',
        readonly=True,
        help='Generated Excel file with proper formatting')
    
    excel_filename = fields.Char(
        string='Excel Filename',
        readonly=True)
    
    # Report data
    line_ids = fields.One2many(
        'pos.esales.report.line',
        'report_id',
        string='Daily Lines',
        help='Daily sales breakdown for the month')
    
    # Summary totals
    total_gross_sales = fields.Monetary(
        string='Total Gross Sales',
        currency_field='currency_id',
        compute='_compute_totals',
        store=True)
    
    total_discounts = fields.Monetary(
        string='Total Discounts',
        currency_field='currency_id',
        compute='_compute_totals',
        store=True)
    
    total_net_sales = fields.Monetary(
        string='Total Net Sales',
        currency_field='currency_id',
        compute='_compute_totals',
        store=True)
    
    total_vatable_sales = fields.Monetary(
        string='Total VATable Sales',
        currency_field='currency_id',
        compute='_compute_totals',
        store=True)
    
    total_vat_amount = fields.Monetary(
        string='Total VAT Amount',
        currency_field='currency_id',
        compute='_compute_totals',
        store=True)
    
    total_vat_exempt_sales = fields.Monetary(
        string='Total VAT-Exempt Sales',
        currency_field='currency_id',
        compute='_compute_totals',
        store=True)
    
    total_zero_rated_sales = fields.Monetary(
        string='Total Zero-Rated Sales',
        currency_field='currency_id',
        compute='_compute_totals',
        store=True)
    
    # Status
    state = fields.Selection([
        ('draft', 'Draft'),
        ('generated', 'Generated'),
        ('submitted', 'Submitted'),
    ], string='Status', default='draft', readonly=True)
    
    user_id = fields.Many2one(
        'res.users',
        string='Generated By',
        readonly=True,
        default=lambda self: self.env.user)
    
    generated_date = fields.Datetime(
        string='Generated Date',
        readonly=True)
    
    submitted_date = fields.Datetime(
        string='Submitted Date',
        readonly=True,
        help='Date when report was marked as submitted to BIR')
    
    # Constraints
    _sql_constraints = [
        ('unique_report_month_company',
         'UNIQUE(report_month, company_id)',
         'Only one eSales report can exist per month per company!')
    ]
    
    @api.depends('report_month', 'company_id')
    def _compute_name(self):
        """Generate report name"""
        for record in self:
            if record.report_month:
                month_str = record.report_month.strftime('%B %Y')
                record.name = f"eSales Report - {month_str}"
            else:
                record.name = "New eSales Report"
    
    @api.depends('bir_config_id', 'report_month')
    def _compute_filename(self):
        """Generate filename as per BIR format"""
        for record in self:
            if record.bir_config_id and record.report_month:
                # Format: POS SALES [TIN][BranchCode] MMYYYY F001.CSV
                tin = record.bir_config_id.tin.replace('-', '').strip()
                # Ensure TIN is 12 digits (pad with zeros if needed)
                if len(tin) == 9:
                    tin = tin + '000'
                elif len(tin) < 12:
                    tin = tin.ljust(12, '0')
                
                branch = record.bir_config_id.branch_code.zfill(2)
                month_year = record.report_month.strftime('%m%Y')
                
                record.filename = f"POS SALES {tin}{branch} {month_year} F001.CSV"
            else:
                record.filename = "ESALES.CSV"
    
    @api.depends('line_ids.gross_sales', 'line_ids.total_discounts', 
                 'line_ids.net_sales', 'line_ids.vatable_sales',
                 'line_ids.vat_amount', 'line_ids.vat_exempt_sales',
                 'line_ids.zero_rated_sales')
    def _compute_totals(self):
        """Compute summary totals from daily lines"""
        for record in self:
            record.total_gross_sales = sum(record.line_ids.mapped('gross_sales'))
            record.total_discounts = sum(record.line_ids.mapped('total_discounts'))
            record.total_net_sales = sum(record.line_ids.mapped('net_sales'))
            record.total_vatable_sales = sum(record.line_ids.mapped('vatable_sales'))
            record.total_vat_amount = sum(record.line_ids.mapped('vat_amount'))
            record.total_vat_exempt_sales = sum(record.line_ids.mapped('vat_exempt_sales'))
            record.total_zero_rated_sales = sum(record.line_ids.mapped('zero_rated_sales'))
    
    def action_generate_csv(self):
        """Generate CSV and Excel files for eSales report"""
        self.ensure_one()
        
        if not self.line_ids:
            raise UserError(_("No daily lines found. Please generate report data first."))
        
        # Generate CSV content
        csv_content = self._generate_csv_content()
        csv_bytes = csv_content.encode('utf-8')
        csv_base64 = base64.b64encode(csv_bytes)
        
        # Generate Excel content
        excel_bytes = self._generate_excel_content()
        excel_base64 = base64.b64encode(excel_bytes)
        
        # Generate Excel filename (replace .CSV with .xlsx)
        excel_filename = self.filename.replace('.CSV', '.xlsx')
        
        # Update record
        self.write({
            'csv_file': csv_base64,
            'csv_filename': self.filename,
            'excel_file': excel_base64,
            'excel_filename': excel_filename,
            'state': 'generated',
            'generated_date': fields.Datetime.now(),
        })
        
        _logger.info(f"eSales CSV and Excel generated: {self.filename}")
        
        # Return action to reload the form view with updated buttons
        return {
            'type': 'ir.actions.act_window',
            'res_model': 'pos.esales.report',
            'res_id': self.id,
            'view_mode': 'form',
            'target': 'current',
        }
    
    def _generate_csv_content(self):
        """Generate CSV file content as per BIR format"""
        self.ensure_one()
        
        output = io.StringIO()
        
        # Header Section (9 rows)
        output.write(f"{self.bir_config_id.business_name or self.company_id.name}\n")
        output.write(f"TIN: {self.bir_config_id.tin}\n")
        output.write(f"Permit#: {self.bir_config_id.permit_number}\n")
        output.write(f"MIN: {self.bir_config_id.min_number or 'N/A'}\n")
        output.write(f"Serial#: {self.bir_config_id.serial_number or 'N/A'}\n")
        output.write(f"Terminal#: {self.bir_config_id.terminal_id or '001'}\n")
        output.write(f"Generated by: {self.user_id.name}\n")
        output.write(f"Printed: {fields.Datetime.now().strftime('%m/%d/%Y %I:%M:%S %p')}\n")
        output.write("\n")  # Blank line
        
        # Column Headers (Row 10)
        headers = [
            'Date',
            'Old Grand Total',
            'New Grand Total',
            'Gross Sales',
            'SC Disc.',
            'PWD Disc.',
            'Athlete/MOV Disc.',
            'Other Disc.',
            'WHT',
            'VAT from Disc.',
            'Total Sales',
            'VATable Sales',
            'VAT Amount',
            'VAT-Exempt Sales',
            'Zero-Rated Sales',
            'Net Sales',
            'Service Charge',
            'Refund',
            'Void',
            'Begin OR',
            'End OR',
            'OR Count',
            'Terminal Read Count',
        ]
        output.write(','.join(headers) + '\n')
        
        # Data Rows (Daily lines)
        lines = self.line_ids.sorted('date')
        for line in lines:
            row = [
                line.date.strftime('%m/%d/%Y'),
                f"{line.old_grand_total:.2f}",
                f"{line.new_grand_total:.2f}",
                f"{line.gross_sales:.2f}",
                f"{line.sc_disc:.2f}",
                f"{line.pwd_disc:.2f}",
                f"{line.athlete_mov_disc:.2f}",
                f"{line.other_disc:.2f}",
                f"{line.whtax:.2f}",
                f"{line.vat_from_disc:.2f}",
                f"{line.total_sales:.2f}",
                f"{line.vatable_sales:.2f}",
                f"{line.vat_amount:.2f}",
                f"{line.vat_exempt_sales:.2f}",
                f"{line.zero_rated_sales:.2f}",
                f"{line.net_sales:.2f}",
                f"{line.service_charge:.2f}",
                f"{line.refund_amount:.2f}",
                f"{line.void_amount:.2f}",
                line.begin_or or '',
                line.end_or or '',
                str(line.or_count),
                str(line.terminal_read_count),
            ]
            output.write(','.join(row) + '\n')
        
        # Summary Row
        first_line = lines[0] if lines else None
        last_line = lines[-1] if lines else None
        
        summary_row = [
            'TOTAL',
            f"{first_line.old_grand_total:.2f}" if first_line else "0.00",
            f"{last_line.new_grand_total:.2f}" if last_line else "0.00",
            f"{self.total_gross_sales:.2f}",
            f"{sum(lines.mapped('sc_disc')):.2f}",
            f"{sum(lines.mapped('pwd_disc')):.2f}",
            f"{sum(lines.mapped('athlete_mov_disc')):.2f}",
            f"{sum(lines.mapped('other_disc')):.2f}",
            f"{sum(lines.mapped('whtax')):.2f}",
            f"{sum(lines.mapped('vat_from_disc')):.2f}",
            f"{sum(lines.mapped('total_sales')):.2f}",
            f"{self.total_vatable_sales:.2f}",
            f"{self.total_vat_amount:.2f}",
            f"{self.total_vat_exempt_sales:.2f}",
            f"{self.total_zero_rated_sales:.2f}",
            f"{self.total_net_sales:.2f}",
            f"{sum(lines.mapped('service_charge')):.2f}",
            f"{sum(lines.mapped('refund_amount')):.2f}",
            f"{sum(lines.mapped('void_amount')):.2f}",
            first_line.begin_or if first_line else '',
            last_line.end_or if last_line else '',
            str(sum(lines.mapped('or_count'))),
            str(sum(lines.mapped('terminal_read_count'))),
        ]
        output.write(','.join(summary_row) + '\n')
        
        return output.getvalue()
    
    def _generate_excel_content(self):
        """Generate Excel file content with proper column widths"""
        self.ensure_one()
        
        # Create workbook
        wb = Workbook()
        ws = wb.active
        ws.title = "eSales Report"
        
        # Header Section (9 rows)
        headers_info = [
            [self.bir_config_id.business_name or self.company_id.name],
            [f"TIN: {self.bir_config_id.tin}"],
            [f"Permit#: {self.bir_config_id.permit_number}"],
            [f"MIN: {self.bir_config_id.min_number or 'N/A'}"],
            [f"Serial#: {self.bir_config_id.serial_number or 'N/A'}"],
            [f"Terminal#: {self.bir_config_id.terminal_id or '001'}"],
            [f"Generated by: {self.user_id.name}"],
            [f"Printed: {fields.Datetime.now().strftime('%m/%d/%Y %I:%M:%S %p')}"],
            [],  # Blank line
        ]
        
        for row_data in headers_info:
            ws.append(row_data)
        
        # Column Headers (Row 10)
        headers = [
            'Date',
            'Old Grand Total',
            'New Grand Total',
            'Gross Sales',
            'SC Disc.',
            'PWD Disc.',
            'Athlete/MOV Disc.',
            'Other Disc.',
            'WHT',
            'VAT from Disc.',
            'Total Sales',
            'VATable Sales',
            'VAT Amount',
            'VAT-Exempt Sales',
            'Zero-Rated Sales',
            'Net Sales',
            'Service Charge',
            'Refund',
            'Void',
            'Begin OR',
            'End OR',
            'OR Count',
            'Terminal Read Count',
        ]
        ws.append(headers)
        
        # Style header row
        header_row = ws[10]
        for cell in header_row:
            cell.font = Font(bold=True)
            cell.alignment = Alignment(horizontal='center')
        
        # Data Rows (Daily lines)
        lines = self.line_ids.sorted('date')
        for line in lines:
            row = [
                line.date.strftime('%m/%d/%Y'),
                float(line.old_grand_total),
                float(line.new_grand_total),
                float(line.gross_sales),
                float(line.sc_disc),
                float(line.pwd_disc),
                float(line.athlete_mov_disc),
                float(line.other_disc),
                float(line.whtax),
                float(line.vat_from_disc),
                float(line.total_sales),
                float(line.vatable_sales),
                float(line.vat_amount),
                float(line.vat_exempt_sales),
                float(line.zero_rated_sales),
                float(line.net_sales),
                float(line.service_charge),
                float(line.refund_amount),
                float(line.void_amount),
                line.begin_or or '',
                line.end_or or '',
                line.or_count,
                line.terminal_read_count,
            ]
            ws.append(row)
        
        # Summary Row
        first_line = lines[0] if lines else None
        last_line = lines[-1] if lines else None
        
        summary_row = [
            'TOTAL',
            float(first_line.old_grand_total) if first_line else 0.00,
            float(last_line.new_grand_total) if last_line else 0.00,
            float(self.total_gross_sales),
            float(sum(lines.mapped('sc_disc'))),
            float(sum(lines.mapped('pwd_disc'))),
            float(sum(lines.mapped('athlete_mov_disc'))),
            float(sum(lines.mapped('other_disc'))),
            float(sum(lines.mapped('whtax'))),
            float(sum(lines.mapped('vat_from_disc'))),
            float(sum(lines.mapped('total_sales'))),
            float(self.total_vatable_sales),
            float(self.total_vat_amount),
            float(self.total_vat_exempt_sales),
            float(self.total_zero_rated_sales),
            float(self.total_net_sales),
            float(sum(lines.mapped('service_charge'))),
            float(sum(lines.mapped('refund_amount'))),
            float(sum(lines.mapped('void_amount'))),
            first_line.begin_or if first_line else '',
            last_line.end_or if last_line else '',
            sum(lines.mapped('or_count')),
            sum(lines.mapped('terminal_read_count')),
        ]
        ws.append(summary_row)
        
        # Style summary row
        summary_row_idx = ws.max_row
        for cell in ws[summary_row_idx]:
            cell.font = Font(bold=True)
        
        # Set column widths
        column_widths = {
            'A': 12,   # Date - wider to prevent #######
            'B': 15,   # Old Grand Total
            'C': 15,   # New Grand Total
            'D': 12,   # Gross Sales
            'E': 10,   # SC Disc.
            'F': 10,   # PWD Disc.
            'G': 15,   # Athlete/MOV Disc.
            'H': 12,   # Other Disc.
            'I': 10,   # WHT
            'J': 12,   # VAT from Disc.
            'K': 12,   # Total Sales
            'L': 13,   # VATable Sales
            'M': 12,   # VAT Amount
            'N': 15,   # VAT-Exempt Sales
            'O': 15,   # Zero-Rated Sales
            'P': 12,   # Net Sales
            'Q': 13,   # Service Charge
            'R': 10,   # Refund
            'S': 10,   # Void
            'T': 12,   # Begin OR
            'U': 12,   # End OR
            'V': 10,   # OR Count
            'W': 17,   # Terminal Read Count
        }
        
        for col, width in column_widths.items():
            ws.column_dimensions[col].width = width
        
        # Format number columns with 2 decimal places
        for row in ws.iter_rows(min_row=11, max_row=ws.max_row, min_col=2, max_col=19):
            for cell in row:
                if isinstance(cell.value, (int, float)) and cell.column <= 19:
                    cell.number_format = '#,##0.00'
        
        # Save to bytes
        output = io.BytesIO()
        wb.save(output)
        output.seek(0)
        
        return output.getvalue()
    
    def action_download_csv(self):
        """Download the generated CSV file"""
        self.ensure_one()
        
        if not self.csv_file:
            raise UserError(_("CSV file has not been generated yet. Please generate it first."))
        
        return {
            'type': 'ir.actions.act_url',
            'url': f'/web/content/pos.esales.report/{self.id}/csv_file/{self.csv_filename}?download=true',
            'target': 'self',
        }
    
    def action_download_excel(self):
        """Download the generated Excel file"""
        self.ensure_one()
        
        if not self.excel_file:
            raise UserError(_("Excel file has not been generated yet. Please generate it first."))
        
        return {
            'type': 'ir.actions.act_url',
            'url': f'/web/content/pos.esales.report/{self.id}/excel_file/{self.excel_filename}?download=true',
            'target': 'self',
        }
    
    def action_mark_submitted(self):
        """Mark report as submitted to BIR"""
        self.ensure_one()
        
        if self.state != 'generated':
            raise UserError(_("CSV file must be generated before marking as submitted."))
        
        self.write({
            'state': 'submitted',
            'submitted_date': fields.Datetime.now(),
        })
        
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Success'),
                'message': _('eSales report has been marked as submitted.'),
                'type': 'success',
                'sticky': False,
            }
        }
    
    def action_reset_to_draft(self):
        """Reset report to draft state"""
        self.ensure_one()
        
        self.write({
            'state': 'draft',
            'csv_file': False,
            'csv_filename': False,
            'excel_file': False,
            'excel_filename': False,
            'generated_date': False,
        })


class PosEsalesReportLine(models.Model):
    """
    Daily line items for eSales Report
    
    Each line represents one day's sales summary
    """
    _name = 'pos.esales.report.line'
    _description = 'eSales Report Daily Line'
    _order = 'date'
    
    report_id = fields.Many2one(
        'pos.esales.report',
        string='eSales Report',
        required=True,
        ondelete='cascade',
        index=True)
    
    date = fields.Date(
        string='Date',
        required=True,
        help='Business date for this line')
    
    currency_id = fields.Many2one(
        'res.currency',
        related='report_id.currency_id',
        readonly=True)
    
    # Grand Totals (Accumulated)
    old_grand_total = fields.Monetary(
        string='Old Grand Total',
        currency_field='currency_id',
        help='Accumulated total from previous days')
    
    new_grand_total = fields.Monetary(
        string='New Grand Total',
        currency_field='currency_id',
        help='Accumulated total including this day')
    
    # Sales Amounts
    gross_sales = fields.Monetary(
        string='Gross Sales',
        currency_field='currency_id',
        help='Total sales before discounts')
    
    # Discount Breakdown
    sc_disc = fields.Monetary(
        string='SC Discount',
        currency_field='currency_id',
        help='Senior Citizen discount')
    
    pwd_disc = fields.Monetary(
        string='PWD Discount',
        currency_field='currency_id',
        help='Person with Disability discount')
    
    athlete_mov_disc = fields.Monetary(
        string='Athlete/MOV Discount',
        currency_field='currency_id',
        help='Athlete or Medal of Valor discount')
    
    other_disc = fields.Monetary(
        string='Other Discounts',
        currency_field='currency_id',
        help='Other types of discounts')
    
    total_discounts = fields.Monetary(
        string='Total Discounts',
        currency_field='currency_id',
        compute='_compute_total_discounts',
        store=True,
        help='Sum of all discounts')
    
    # Tax Related
    whtax = fields.Monetary(
        string='Withholding Tax',
        currency_field='currency_id',
        help='Withholding tax amount')
    
    vat_from_disc = fields.Monetary(
        string='VAT from Discounts',
        currency_field='currency_id',
        help='VAT amount from discount transactions')
    
    # Sales Breakdown
    total_sales = fields.Monetary(
        string='Total Sales',
        currency_field='currency_id',
        help='Total sales after discounts')
    
    vatable_sales = fields.Monetary(
        string='VATable Sales',
        currency_field='currency_id',
        help='Sales subject to 12% VAT (net of VAT)')
    
    vat_amount = fields.Monetary(
        string='VAT Amount',
        currency_field='currency_id',
        help='12% VAT on VATable sales')
    
    vat_exempt_sales = fields.Monetary(
        string='VAT-Exempt Sales',
        currency_field='currency_id',
        help='Sales exempt from VAT (SC/PWD)')
    
    zero_rated_sales = fields.Monetary(
        string='Zero-Rated Sales',
        currency_field='currency_id',
        help='Zero-rated sales')
    
    net_sales = fields.Monetary(
        string='Net Sales',
        currency_field='currency_id',
        help='Final net sales amount')
    
    # Other Amounts
    service_charge = fields.Monetary(
        string='Service Charge',
        currency_field='currency_id',
        help='Service charge amount')
    
    refund_amount = fields.Monetary(
        string='Refund Amount',
        currency_field='currency_id',
        help='Total refund amount')
    
    void_amount = fields.Monetary(
        string='Void Amount',
        currency_field='currency_id',
        help='Total voided transactions amount')
    
    # Receipt Range
    begin_or = fields.Char(
        string='Begin OR',
        help='First Official Receipt number for this date')
    
    end_or = fields.Char(
        string='End OR',
        help='Last Official Receipt number for this date')
    
    or_count = fields.Integer(
        string='OR Count',
        help='Number of Official Receipts issued')
    
    terminal_read_count = fields.Integer(
        string='Terminal Read Count',
        help='Number of terminal reads/transactions')
    
    @api.depends('sc_disc', 'pwd_disc', 'athlete_mov_disc', 'other_disc')
    def _compute_total_discounts(self):
        """Compute total discounts"""
        for line in self:
            line.total_discounts = (
                line.sc_disc +
                line.pwd_disc +
                line.athlete_mov_disc +
                line.other_disc
            )

